# -*- coding: utf-8 -*-
"""EMA-RSI14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMpzgZaZTa83YNXyFld_A0YLQ3SVpPUo
"""

!pip install pandas_ta -q

import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import matplotlib.pyplot as plt

TICKER = "EURUSD=X"
PERIOD = "5y"
INTERVAL = "1d"

EMA_FAST = 9
EMA_SLOW = 21
RSI_LEN = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

TRADING_DAYS = 252

df = yf.download(TICKER, period=PERIOD, interval=INTERVAL)

if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df[['Open', 'High', 'Low', 'Close', 'Volume']].copy()

df['ema_fast'] = ta.ema(df['Close'], length=EMA_FAST)
df['ema_slow'] = ta.ema(df['Close'], length=EMA_SLOW)
df['rsi'] = ta.rsi(df['Close'], length=RSI_LEN)

df.dropna(inplace=True)

cross_up = (df['ema_fast'] > df['ema_slow']) & (df['ema_fast'].shift(1) <= df['ema_slow'].shift(1))
cross_down = (df['ema_fast'] < df['ema_slow']) & (df['ema_fast'].shift(1) >= df['ema_slow'].shift(1))

df['long_entry'] = cross_up & (df['rsi'] < RSI_OVERBOUGHT)
df['long_exit'] = cross_down & (df['rsi'] > RSI_OVERSOLD)

position = 0
positions = []
for entry, exit_ in zip(df['long_entry'], df['long_exit']):
    if position == 0 and entry:
        position = 1
    elif position == 1 and exit_:
        position = 0
    positions.append(position)

df['position'] = positions

df['returns'] = df['Close'].pct_change()
df['strategy_returns'] = df['position'].shift(1) * df['returns']
df.dropna(inplace=True)

df['equity_curve'] = (1 + df['strategy_returns']).cumprod()
df['buy_hold_curve'] = (1 + df['returns']).cumprod()

total_return = df['equity_curve'].iloc[-1] - 1
buy_hold_return = df['buy_hold_curve'].iloc[-1] - 1

mean_ret = df['strategy_returns'].mean()
std_ret = df['strategy_returns'].std()
sharpe = (mean_ret / std_ret) * np.sqrt(TRADING_DAYS) if std_ret != 0 else np.nan

downside_std = df['strategy_returns'][df['strategy_returns'] < 0].std()
sortino = (mean_ret / downside_std) * np.sqrt(TRADING_DAYS) if downside_std != 0 else np.nan

rolling_max = df['equity_curve'].cummax()
drawdown = (df['equity_curve'] - rolling_max) / rolling_max
max_drawdown = drawdown.min()

num_trades = int(df['long_entry'].sum())
win_rate = (df.loc[df['position'] == 1, 'strategy_returns'] > 0).mean()

print("===== STRATEGY: EMA Crossover + RSI Filter =====")
print(f"Period             : {df.index[0].date()} to {df.index[-1].date()}")
print(f"Total Return       : {total_return:.2%}")
print(f"Buy & Hold Return  : {buy_hold_return:.2%}")
print(f"Sharpe Ratio       : {sharpe:.2f}")
print(f"Sortino Ratio      : {sortino:.2f}")
print(f"Max Drawdown       : {max_drawdown:.2%}")
print(f"Number of Trades   : {num_trades}")
print(f"Win Rate (in-pos)  : {win_rate:.2%}")

fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True,
                          gridspec_kw={'height_ratios': [3, 1, 2]})

axes[0].plot(df.index, df['Close'], label='Close', color='black', linewidth=1)
axes[0].plot(df.index, df['ema_fast'], label=f'EMA{EMA_FAST}', color='blue')
axes[0].plot(df.index, df['ema_slow'], label=f'EMA{EMA_SLOW}', color='orange')
axes[0].scatter(df.index[df['long_entry']], df['Close'][df['long_entry']],
                marker='^', color='green', s=80, label='Long Entry', zorder=5)
axes[0].scatter(df.index[df['long_exit']], df['Close'][df['long_exit']],
                marker='v', color='red', s=80, label='Long Exit', zorder=5)
axes[0].set_title(f'{TICKER} - EMA{EMA_FAST}/EMA{EMA_SLOW} + RSI({RSI_LEN}) Filter')
axes[0].legend()

axes[1].plot(df.index, df['rsi'], color='purple')
axes[1].axhline(RSI_OVERBOUGHT, color='red', linestyle='--')
axes[1].axhline(RSI_OVERSOLD, color='green', linestyle='--')
axes[1].set_title('RSI')
axes[1].set_ylim(0, 100)

axes[2].plot(df.index, df['equity_curve'], label='Strategy', color='blue')
axes[2].plot(df.index, df['buy_hold_curve'], label='Buy & Hold', color='gray', linestyle='--')
axes[2].set_title('Equity Curve')
axes[2].legend()

plt.tight_layout()
plt.show()